clean: don't abort on cleanup errors
Previously clean would abort on the first project which failed to clean.
Generally this shouldn't happen, but may happen e.g. if an earlier
procedure was aborted with ^C - which may confuse "make clean".

Now we just warn on such cases and still try to clean all requested
projects, though eventually exit with error if at least one cleanup
failed.

diff --git a/clean b/clean
--- a/clean
+++ b/clean
@@ -14,14 +14,20 @@ config_process_projects_cli=yes
 
 hook_or_die "$config_clean_pre" clean-pre
 
+# on errors we warn and continue, but finally exit with error code 1
+fail=
 for p in $config_projects; do
     highlight_msg "($config_projects) cleaning $p"
-    scripts/${p}-clean || err_msg_die "failed to clean '$p'"
+    scripts/${p}-clean || { warn_msg "failed to clean '$p'"; fail=yes; }
 done
 
 if [ no = "$keep_prefix" ]; then
-    rm -rf "$config_local_prefix"
+    highlight_msg "($config_projects) deleting local prefix dir"
+    rm -rf "$config_local_prefix" ||
+        { warn_msg "failed to delete '$config_local_prefix'"; fail=yes; }
 fi
 
 hook_or_die "$config_clean_post" clean-post
+
+[ "$fail" ] && warn_msg "($config_projects) some cleanups failed" && exit 1
 success_msg "cleaned: $config_projects"
