update: revise: [shallow] head/release/rebase/^remote-ref/@rev/!hook
This commit changes the default updates from "master" to "-head" which
is the same as before but shallow. See below.

This commit revises the update options:
- Changes "master" to "head" because it's more correct.
- Change @BAR to just checkout BAR without fetch.
- Adds ^BAZ to fetch and checkout a latest remote-ref [fuzzy] BAZ.
- Adds !FOO to run hook FOO instead of doing anything ourselves
- Support '-' prefix for "shallow" with modes which fetch.

See config/default.conf for summary of the update options and examples.

Technically, it now uses git ls-remote to find which references are
available before fetching (used by "release" and "^BAZ"), and allows
shallow fetches while pointing to them from a local git reference such
subsequent shallow fetches can at least use some delta.

diff --git a/update b/update
--- a/update
+++ b/update
@@ -22,23 +22,102 @@ versort_with_prefix() {
     # grep "^$2[0-9]" | sort -V
 }
 
-# $1: tag prefix
-highest_release_tag() {
-    local tag="$(git tag | grep -v rc | grep -v dev | versort_with_prefix "$1" | tail -n 1)"
-    [ $? = 0 ] && [ "$tag" ] || err_msg_die "cannot find release tags with prefix '$1'"
-    printf %s "$tag"
+remote_tags() {
+    # tags ending with ^{} are refs to other tags with the same name sans ^{}
+    git ls-remote --tags | cut -f2 | grep -v '\^{}$' | sed "s/^refs\/tags\///g"
 }
 
-# $1: repo dir, 2: update value to perform at the repo, $3: release prefix
+# $1: tag prefix
+highest_release_tag_ref() {
+    local tag="$(remote_tags | grep -v rc | grep -v dev | versort_with_prefix "$1" | tail -n 1)"
+    [ $? = 0 ] && [ "$tag" ] || return 1
+    printf %s "refs/tags/$tag"
+}
+
+# $1: repo URL, $2: repo dir [,$3: non empty if shallow update]
+ensure_repo() { (
+    if [ -e "$2" ]; then
+        cd "$2" &&
+        git remote set-url origin "$1"
+    else
+        if [ -z "${3-}" ]; then
+            # not shallow -> plain clone
+            git clone "$1" "$2"
+        else
+            # shallow -> init the repo without fetching anything
+            mkdir -p "$2" &&
+            cd "$2" &&
+            git init &&
+            git remote add origin "$1"
+        fi
+    fi
+) || err_msg_die "cannot setup git repo '$2' at '$3'"; }
+
+# resolve a full remote ref from [fuzzy] $1, or fail
+remote_ref() (
+    set +x
+    refs="$(git ls-remote | cut -f2 | grep -v '\^{}$')" || exit 1
+
+    # we only know to handle HEAD or refs/*
+    [ HEAD = "$1" ] && printf HEAD ||
+    (printf %s "$refs" | grep "^refs/${1#refs/}\$") ||
+    (printf %s "$refs" | grep "^refs/tags/$1\$") ||
+    (printf %s "$refs" | grep "^refs/heads/$1\$") ||
+    (printf %s "$refs" | grep "^refs/pull/(${1#pull/}\|${1#PR}/head\$")  # pull/42, PR42, 42
+)
+
+# $1: remote ref, [$2 ... : earlier fetch args]
+# tries to create a local reference for known types (tags/heads/pull) such that
+# subsequent fetches may fetch only delta, else checkout the temp FETCH_HEAD
+fetch_checkout() (
+    f="$1"        # default fetch ref arg - without a local ref
+    c=FETCH_HEAD  # default checkout arg
+    shift
+
+    case "$f" in
+        # create local reference using remote-ref:local-ref syntax.
+        refs/tags/*)  c="$f"                                   && f="$f:$c";;
+        refs/heads/*) c="refs/remotes/origin/${f#refs/heads/}" && f="$f:$c";;
+        refs/pull/*)  c="refs/remotes/origin/${f#refs/}"       && f="$f:$c";;
+        HEAD)         c="refs/remotes/origin/HEAD"             && f="$f:$c";;
+    esac
+    git fetch "$@" origin "$f" && git checkout "$c"^0
+)
+
+# $1: update value, $2: repo URL, $3: repo dir, $4: release prefix
 update_source_or_die() { (
-    set -ex
-    cd "$1"
-    case "$2" in
-         rebase) git pull --rebase;;
-         master) git fetch && git checkout origin/master;;
-        release) git fetch --tags && git checkout "refs/tags/$(highest_release_tag "$3")";;
-             @*) git fetch --tags && git checkout "${2#@}";;
-              *) err_msg_die "Unknown update type '$2'"
+    set +x
+
+    ref=
+    update="$1"
+    depth=
+    # if update starts with '-' (shallow) -> strip it + set $depth
+    case "$update" in -*)
+        update="${update#-}"
+        # determines how many commits can happen upstream before shallow
+        # fetch begins from scratch. 100 is an arbitrary balance.
+        depth="--depth=100"
+    esac
+
+    set -x
+    ensure_repo "$2" "$3" "$depth" &&
+    cd "$3" &&
+    case "$update" in
+            @*) git checkout "${update#@}";;
+        rebase) git pull $depth --rebase;;
+          head) fetch_checkout HEAD $depth;;
+
+       release) ref="$(highest_release_tag_ref "$4")" ||
+                    err_msg_die "cannot find release tags with prefix '$4'"
+                fetch_checkout "$ref" $depth
+                ;;
+
+            ^*) ref="$(remote_ref "${update#^}")" ||
+                    err_msg_die "cannot find remote ref '${update#^}'"
+                fetch_checkout "$ref" $depth
+                ;;
+
+            *) err_msg_die "Unknown update type '$1'"
     esac
 ) || err_msg_die "update failed"; }
 
@@ -47,14 +126,15 @@ hook_or_die "$config_update_pre" update-pre
 for p in $config_projects; do
     update="$(var_val config_${p}_update)"
     highlight_msg "($config_projects) updating $p/$update"
-    [ none = "$update" ] && continue
 
-    url="$(var_val config_${p}_git)"
-    dir="$(var_val config_${p}_source)"
-    rel_prfx="$(var_val config_${p}_release_prefix)"
-
-    [ -e "$dir" ] || git clone "$url" "$dir" || err_msg_die "cannot clone '$url' to '$dir'"
-    update_source_or_die "$dir" "$update" "$rel_prfx"
+    case "$update" in
+        none) continue;;
+          !*) hook_or_die "${update#!}" $p;;
+           *) update_source_or_die  "$update" \
+                "$(var_val config_${p}_git)" \
+                "$(var_val config_${p}_source)" \
+                "$(var_val config_${p}_release_prefix)"
+    esac
 
     hook_or_die "$(var_val config_${p}_update_post)" ${p}-update-post
 done
