rewrite of clean/update/build - separate process from data
Previously the process (driving the clean/build etc) was mixed with the
data as part of the script, now the script are only the process, while
all of the data is at config files.

The config is now in 3 stages:
- ./config/default.conf (shell script) which is part of the repo.
- ./user.conf is overlayed on top of default.conf and can override it.
- CLI arguments can modify some values further, but leave no permanent
  traces on the config and their effect is limited to te runtime when used.

The config now controls the following:
- The list of projects to process, and the processing order.
- Projects git repo and update policy (release/master/custom/none/rebase).
- Projects source code dirs.
- Local install prefix.
- User hooks which can be set to run before/after clean/update/build.

CLI arguments can override the list of projects and per-project update
policy, as well as specify build arguments.

E.g. ./rebuild libass ffmpeg/master mpv/@v0.27.0 -j8

- The list of projects is libass/ffmpeg/mpv which clean/update/build process.
- The update policy for libass is from the config files, for ffmpeg is
  master, and for mpv a specific thing to checkout.
- Same build arguments -j8 are used by build for the three projects.

Per-project configure options is like before via files <proj>_options .

TODO:
- Update the docs (config/default.conf is self documented, but we need more).

- The debian makefile is not yet touched - it assumes the stages scripts
  (scripts/libass-build etc) are stand alone but now they're not anymore
  as the hardcoded paths were replaced with config values. Either make
  them stand alone by reading the config files or use the higher level
  and now more flexible build/clean/etc scripts.

- Enhancement: Support shallow clone. Should be possible, and we should
  probably add it at some stage.

- Enhancement: support more libs to build, which now is just a matter of
  adding few details to the config and their clean/config/build scripts.

diff --git a/scripts/debian-update-versions b/scripts/debian-update-versions
--- a/scripts/debian-update-versions
+++ b/scripts/debian-update-versions
@@ -14,10 +14,28 @@ get_version()
     )
 }
 
+# $1: main project name, $2 main project revision, $3: "lib1-name lib1-rev, ..."
 do_subst() {
-    sed  -e "0,/^mpv (.*)/s/(.*)/($1)/" \
-	      -e "s/^  \* local build.*/  \* local build with ffmpeg $2, libass $3/" \
+    sed  -e "0,/^$1 (.*)/s/(.*)/($2)/" \
+	      -e "s/^  \* local build.*/  \* local build with $3/" \
 	      -e"s/\(^ -- Local User <localuser@localhost>\).*/\1  $(date -R)/" debian/changelog.TEMPLATE > debian/changelog
 }
 
-do_subst $(get_version mpv) $(get_version ffmpeg) $(get_version libass)
+# args: $1: valid variable name to print its value
+var_val() { eval printf %s \"\$$1\"; }
+
+# args: individual names of the active projects - the last is considered main.
+update_changelog() {
+    local deps=
+    [ $# = 0 ] && echo "Error: no project names" && exit 1
+    while [ $# -gt 1 ]; do
+        [ "$deps" ] && deps="$deps, "
+        deps="$deps$1 $(get_version "$(var_val "config_${1}_source")")"
+        shift
+    done
+    [ "$deps" ] || deps="no local libs"
+
+    do_subst "$1" "$(get_version "$(var_val "config_${1}_source")")" "$deps"
+}
+
+update_changelog $config_projects
diff --git a/update b/update
--- a/update
+++ b/update
@@ -1,146 +1,63 @@
 #!/bin/sh
 export LC_ALL=C
 
-do_clone()
-{
-    set -ex
-    if ! test -e "$1" ; then
-        git clone "$2" "$1"
-    fi
-    (
-        cd "$1"
-        git remote set-url origin "$2"
-        git fetch
-    )
-}
-
-do_clone_all()
-{
-    do_clone "ffmpeg"   "https://github.com/FFmpeg/FFmpeg.git"
-    #do_clone "fribidi"  "http://anongit.freedesktop.org/git/fribidi/fribidi.git"
-    do_clone "libass"   "https://github.com/libass/libass.git"
-    do_clone "mpv"      "https://github.com/mpv-player/mpv.git"
-}
-
-do_gitmaster()
-{
-    set -ex
-    (
-        cd "$1"
-        git checkout origin/master
-        git remote prune origin
-    )
-}
-
-versort_with_prefix()
-{
-	# Emulate sort -V using a known prefix. Filter out anything else.
-	sed -n -e "s/^$1\([0-9]\)/\\1/p" |\
-		sort -n -t . -k 1,1 -k 2,2 -k 3,3 -k 4,4 |\
-		sed -e "s/^/$1/"
-	# GNU version of the same:
-	# grep "^$2[0-9]" | sort -V
-}
-
-do_releasetag()
-{
-    local prefix=  # by default, don't use a prefix
-    case "$1" in
-        ffmpeg) prefix=n;;  # e.g. n3.3.1
-        mpv)    prefix=v;;  # e.g. v0.26.0
-    esac
-
-    (
-        cd "$1"
-        version=`git tag | grep -v rc | grep -v dev | versort_with_prefix "$prefix" | tail -n 1`
-        git checkout refs/tags/"$version"
-    )
-}
-
-do_fixedref()
-{
-    (
-        cd "$1"
-        git checkout "$2"
-    )
-}
-
-# args: $1: project name, $2: release/master/@foo [,$3: non-empty to ignore the config file]
-checkout()
-{
-    local branch="$2"
-    if [ -z "$3" ] && [ -d config/ ] && [ -f config/branch-$1 ]; then
-        branch="$(cat config/branch-$1)"
-    fi
-
-    case "$branch" in
-        master)  do_gitmaster $1;;
-        release) do_releasetag $1;;
-        @*)      do_fixedref $1 "${branch#@}";;  # everything after the '@' prefix
-        *)       >&2 printf "%s\n" "Error: Don't know how to checkout '$branch'"
-                 return 1
-    esac
-}
-
-# fallback targets: release/master/@foo if no config file
-checkout_ffmpeg=master
-#checkout_fribidi=release
-checkout_libass=master
-checkout_mpv=master
-
-
-checkout_all()
-{
-    set -ex
-    do_clone_all
-    checkout ffmpeg $checkout_ffmpeg
-    #$checkout fribidi $checkout_fribidi
-    checkout libass $checkout_libass
-    checkout mpv $checkout_mpv
-}
-
-do_bootstrap()
-{
-  scripts/mpv-bootstrap
-}
-
-do_update_debian_versions()
-{
-  scripts/debian-update-versions $1
-}
-
-if [ x"$1" != x"--skip-selfupdate" ]; then
-    (
-        set -ex
-        git pull --rebase
-    )
+if [ x"${1:-}" != x"--skip-selfupdate" ]; then
+    # try self-update of this repo (don't abort on failure) and re-run.
+    (set -ex && cd "$(dirname "$0")" && git pull -r) || echo "Warning: cannot self-update"
     exec "$0" --skip-selfupdate "$@"
 fi
 shift
 
-# allow checkout master/release without checking the config files
-case "$1" in
-    --master)
-        checkout_ffmpeg="master -"
-        #checkout_fribidi="master -"
-        checkout_libass="master -"
-        checkout_mpv="master -"
-        ;;
-    --release)
-        checkout_ffmpeg="release -"
-        checkout_mpv="release -"
-        ;;
-    '')
-        ;;
-    *)
-        echo >&2 "$0 --master"
-        echo >&2 "$0 --release"
-        exit 0
-        ;;
-esac
+cd "$(dirname "$0")"
+config_process_projects_cli=yes
+. scripts/core-config || exit 1
 
-checkout_all
+# $1: tag prefix
+versort_with_prefix() {
+    # Emulate sort -V using a known prefix. Filter out anything else.
+    sed -n -e "s/^$1\([0-9]\)/\\1/p" |\
+        sort -n -t . -k 1,1 -k 2,2 -k 3,3 -k 4,4 |\
+        sed -e "s/^/$1/"
+    # GNU version of the same:
+    # grep "^$2[0-9]" | sort -V
+}
 
-do_update_debian_versions
+# $1: tag prefix
+highest_release_tag() {
+    local tag="$(git tag | grep -v rc | grep -v dev | versort_with_prefix "$1" | tail -n 1)"
+    [ $? = 0 ] && [ "$tag" ] || err_msg_die "cannot find release tags with prefix '$1'"
+    printf %s "$tag"
+}
 
-do_bootstrap
+# $1: repo dir, 2: update value to perform at the repo, $3: release prefix
+update_source_or_die() { (
+    set -ex
+    cd "$1"
+    case "$2" in
+         rebase) git pull --rebase;;
+         master) git fetch && git checkout origin/master;;
+        release) git fetch --tags && git checkout "refs/tags/$(highest_release_tag "$3")";;
+             @*) git fetch --tags && git checkout "${2#@}";;
+              *) err_msg_die "Unknown update type '$2'"
+    esac
+) || err_msg_die "update failed"; }
+
+hook_or_die "$config_update_pre" update-pre
+
+for p in $config_projects; do
+    url="$(var_val config_${p}_git)"
+    dir="$(var_val config_${p}_source)"
+    update="$(var_val config_${p}_update)"
+    rel_prfx="$(var_val config_${p}_release_prefix)"
+
+    highlight_msg "($config_projects) updating $p/$update"
+    [ -e "$dir" ] || git clone "$url" "$dir" || err_msg_die "cannot clone '$url' to '$dir'"
+    [ "$update" = "none" ] || update_source_or_die "$dir" "$update" "$rel_prfx"
+
+    hook_or_die "$(var_val config_${p}_update_post)" ${p}-update-post
+done
+
+scripts/debian-update-versions || err_msg_die "cannnot update debian versions"
+
+hook_or_die "$config_update_post" update-post
+success_msg "updated: $config_projects"
